### PR TITLE
Add the ability to force a camera update

### PR DESCRIPTION
**Pull request by bdraco**
Allows updating the switch state right away

### CODE REVIEW

**Comment by briis** [comment]
I am not a Github shark, and this seems not to be ready for merging?

**Comment by bdraco** [comment]
I'm still testing....probably another 5-10m. As soon as its good to go I'll convert it from a draft.

**Comment by bdraco** [comment]
Good to go now

**Comment by briis** [comment]
Check. Uploaded as 0.22.0

**Pull request merged**
