### PR TITLE
Add support for motion detection when recording is off

### PR DESCRIPTION
**Pull request by bdraco**
Uses the `lastMotion` and `isMotionDetected` events to construct the camera event update.

Verified it switches back to using `events` which gets us scores etc when recording is turned back on.

### CODE REVIEW

**Comment by bdraco** [comment]
Verified working

```
2020-11-19 20:37:12 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605818229503, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:37:17 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605818229503, 'event_length': 8.184, 'event_score': 0}
2020-11-19 20:37:18 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605818235810, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:37:22 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605818235810, 'event_length': 6.863, 'event_score': 0}
2020-11-19 20:40:15 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605818412690, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:40:20 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605818412690, 'event_length': 8.154, 'event_score': 0}
2020-11-19 20:48:27 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605818904222, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:48:39 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605818904222, 'event_length': 14.989, 'event_score': 0}
2020-11-19 20:52:40 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605819157796, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:52:45 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605819157796, 'event_length': 8.179, 'event_score': 0}
2020-11-19 20:53:06 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605819183380, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:53:09 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605819183380, 'event_length': 6.316, 'event_score': 0}
2020-11-19 20:57:26 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': True, 'event_type': 'motion', 'event_start': 1605819443032, 'event_length': 0.0, 'event_score': 0}
2020-11-19 20:57:31 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Processed camera event: {'event_on': False, 'event_type': 'motion', 'event_start': 1605819443032, 'event_length': 8.195, 'event_score': 0}
```

**Comment by briis** [comment]
I have been OFF. Will merge now and do tests in the weekend.

**Comment by briis** [comment]
GREAT work on this Nick. Here are my findings after testing this merge
* Motion detection with Recording mode set to *never*, works very well
* When recording mode is set to never, and motion is active - if you then switch to any kind of recording mode, it takes the motion sensor a long time before it goes to off. Eventually it will go off. Not a breaking issue.
* When the doorbell is pressed, the ring sensor registers it, but is reset within milliseconds. I made an automation to test if HA can capture that switch to the on state, and it works.
* Fixed the highFPS switch. It turned out that this was an issue in the Integration itself. We were sending a text string of either highFPS or default to the service, and it has to be True or False.

**Comment by briis** [comment]
One more thing I discovered when going through the raw json data of the cameras, is that there is now a second SmartDetectType called `vehicle`. I believe it is easy to add to the `event_from_ws_frames` but I will let you do it, to make sure it comes in correctly and that I do not miss anything.

The below is how it looks in the raw json:

```json
    "smartDetectTypes": [
     "person",
     "vehicle"
    ],
```

**Comment by bdraco** [comment]
Since we are doing `"event_object": event.get("smartDetectTypes")`, I think its already going to feed back the `vehicle` without any changes

**Comment by briis** [comment]
Sounds plausible. Honestly, I couldn't convince my wife to drive in and out the driveway to test it.

**Comment by briis** [comment]
Hi Nick,
I did a bit more testing and could not find any errors. Do we agree this is ready for release?

About the vehicle object. It is currently not available in the App or WebApp, to enable that, so it must be a future thing. Let us see when it gets available, if it works. (I even tried to activate it through the API, but could also not get it to work.)

**Comment by bdraco** [comment]
> Hi Nick,
> I did a bit more testing and could not find any errors. Do we agree this is ready for release?

I think is it is ready to go 👍 
> 
> About the vehicle object. It is currently not available in the App or WebApp, to enable that, so it must be a future thing. Let us see when it gets available, if it works. (I even tried to activate it through the API, but could also not get it to work.)

I expect its incomplete and once UI does another release we can take another look to see if its ready for use (hopefully it just works)!

**Comment by briis** [comment]
I will pack it up tomorrow morning my time, and release it. Thank for the great work.

**Comment by bdraco** [comment]
> I will pack it up tomorrow morning my time, and release it. Thank for the great work.

Excellent. Thanks Bjarne!

**Pull request merged**
