### PR TITLE
Moved to device vs. camera

### PR DESCRIPTION
**Pull request by briis**
Still missing the Services to change things on the Floodlight, but wanted to agree on structure first.

### CODE REVIEW

**Review by bdraco — APPROVED** [review]
LGTM

**Comment by bdraco** [comment]
Is there an option to disable/enable motion detection for the light in the UI?  If not we can probably remove the code to generate events from the `light` model since we can likely assume there will always be events if there isn't an option.

**Comment by briis** [comment]
No, motion detection by itself, cannot be disabled - it's like the cameras. You can however set the floodlight so that motion on the PIR turns on the light: always, when it is dark or disable it.

So your suggestion should work. I am not sure exactly what part of the code you would remove?

**Comment by bdraco** [comment]
> No, motion detection by itself, cannot be disabled - it's like the cameras. You can however set the floodlight so that motion on the PIR turns on the light: always, when it is dark or disable it.
> 
> So your suggestion should work. I am not sure exactly what part of the code you would remove?

I implemented that in https://github.com/briis/pyunifiprotect/pull/21  I don't have a way of testing it though

**Pull request merged**
