### PR TITLE
Removes deprecated unifi_ code. Drop 3.8 support. Upgrade mypy to pyproject.toml

### PR DESCRIPTION
**Pull request by AngellusMortis**
Now that pydantic _finally_ released 1.9.0, now is a good time to do a bunch of upgrades. Starting with 

* remove `UpvServer` and any remaining code that uses it
* remove Python 3.8 support
* replace `mypy.ini` with config in `pyproject.toml`

### CODE REVIEW

**Comment by bdraco** [comment]
I might be a bit early to drop 3.8 since core dev still supports it

https://github.com/home-assistant/core/blob/dev/homeassistant/const.py#L13

**Comment by AngellusMortis** [comment]
It is suppose to be removed soon. It was originally going to be 2022.1,but that release was canceled.

https://www.home-assistant.io/blog/2021/11/03/release-202111/

**Comment by AngellusMortis** [comment]
Oh, found the drop PR to remove support: https://github.com/home-assistant/core/pull/62340

**Comment by bdraco** [comment]
If we need to do a release of this before 2022.2 it would put us in a bit of a bind since there may still be users using 3.8

**Review by bdraco — APPROVED** [review]

**Pull request merged**
