### PR TITLE
Skip cameras that are not present in the state machine

### PR DESCRIPTION
**Pull request by bdraco**
I added `has_camera` to the state machine so we can skip cameras that aren't present.

### CODE REVIEW

**Comment by bdraco** [comment]
Running this for a bit to make sure that it still addresses the error before I mark it ready for review.

I didn't wait long enough on the previous PR. The non-adopted camera updates are very infrequent for my test setup so I want to make sure this runs for at least an hour without error before I mark it ready

**Comment by briis** [comment]
Yes, I saw the same when I tried to fix it this afternoon - It took a little while before the errors started.
You just push it, when it's ready.

**Comment by bdraco** [comment]
Looks good after running for an hour 👍

**Comment by briis** [comment]
Perfect, thanks. 
I'll merge it. 

Have a good weekend.

**Pull request merged**
