### PR TITLE
Only update cameras detail every 60s (Keep events at every 2s)

### PR DESCRIPTION
**Pull request by bdraco**
My protect server saw a cpu spike and was a few
degrees warmer after installing the unifiprotect
integration due to the frequent polling.  When there
are >10 cameras this problem is much worse.

The bootstrap api is an expensive api to run
every 2s, which is the current update interval.
The calls to bootstrap are enough to have
a measurable impact on the event loop

The events api is rather cheap so its not a concern.

### CODE REVIEW

**Comment by bdraco** [comment]
I wasn't 100% sure if the `last_ring` and `last_motion` should have been the start or end time.

**Comment by bdraco** [comment]
Before (all data coordinator updates):
pyunifiprotect is most of my instances entire data update coordinator overhead.
Screen Shot 2020-06-13 at 10 25 32 AM

After (all data coordinator updates):
pyunifiprotect doesn't show up in the data update coordinator overhead.
Screen Shot 2020-06-13 at 10 25 59 AM

**Comment by briis** [comment]
Hi @bdraco 
Thanks for the PR, I "only" have 4 Cameras so I did not notice that. But I do agree that there is information we don't need every 2 seconds. I will upload this as version 0.16 to PyPi, but I need the only guy I know with a Doorbell to test it before I change the manifest on the Unifi Protect Integration.

**Comment by briis** [comment]
Another thought: Isn't there a way in Python to create an indefinite loop, that monitors the event stream in the background, and then pushes the information back to Home Assistant? Then we could just set the Pull frequency to 60 seconds for the Camera data and listen for the Events?

I am not a skilled Python programmer, everything I can do, I learned from guys like you, and watching what others have done, so I would have no idea where to start, but I would guess it would be some kind of Callback?

**Comment by bdraco** [comment]
> Another thought: Isn't there a way in Python to create an indefinite loop, that monitors the event stream in the background, and then pushes the information back to Home Assistant? Then we could just set the Pull frequency to 60 seconds for the Camera data and listen for the Events?
> 
> I am not a skilled Python programmer, everything I can do, I learned from guys like you, and watching what others have done, so I would have no idea where to start, but I would guess it would be some kind of Callback?

If the protect server can deliver events over a websocket, a callback can be used to get them i near real-time.  I know the unifi controller has some form of websocket support but I'm not that familiar with the protect api.

**Comment by briis** [comment]
Thanks - I don't know either, but I could poke around to see. Do you know of a good example where this is implemented? Then I could play with it, if I find that Protect is delivering data.

**Comment by bdraco** [comment]
> Thanks - I don't know either, but I could poke around to see. Do you know of a good example where this is implemented? Then I could play with it, if I find that Protect is delivering data.
> 

Here is an example of websocket use with the ambient weather integration.
https://github.com/bachya/aioambient/blob/dev/aioambient/websocket.py

> Btw: If it was not clear, the V0.16, with your changes, is uploaded to PyPi, so you can change your manifest already now to use that version.

Thanks.  I had manually patched it :)

**Comment by briis** [comment]
> Here is an example of websocket use with the ambient weather integration.
https://github.com/bachya/aioambient/blob/dev/aioambient/websocket.py

Thanks. I will see if I can figure something out in the next weeks.

**Pull request merged**
