### PR TITLE
Minor fixes for timezones / aiohttp warnings

### PR DESCRIPTION
**Pull request by AngellusMortis**
* Fixes timezone issue with `to_js_time` when a naïve datetime was passed in
* Fixes a warning that was appearing in pytest for py=3.10 about creating aiohttp sessions outside of an async context. I am guessing this would have turned into an error in 3.11.
* Ensures outside of `unifi_protect_server.py` all `datetime.now` calls are replaced with new `utc_now` helper method that return `datetime.utcnow()` with a tzinfo so it is not naive.
* Fixes issues with tests if no motion event is found.

## HA Install Link:

```
git+https://github.com/AngellusMortis/pyunifiprotect.git@bugfix/timezones#pyunifiprotect==1.1
```

### CODE REVIEW

**Comment by AngellusMortis** [comment]
Okay. I decided to refactor and simplify the public interface for the API client. None of the internal session/Websocket should be "public" anymore.

I doubt checked that the `unifiprotect` does not use any of use any of those fields, so no breakage should occur upstream.

**Review by bdraco — COMMENTED** [review]
Changes look fine, I'm not in position to test right now though

**Comment by bdraco** [comment]
Looks like something might need an adjustment

```
pyunifiprotect.exceptions.NvrError: Call https://192.168.210.83/api/auth/login received 404 Not Found
2021-11-14 11:32:41 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 430, in _handle_request
    resp = await request_handler(request)
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/Users/bdraco/home-assistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/Users/bdraco/home-assistant/homeassistant/components/camera/__init__.py", line 612, in get
    return await self.handle(request, camera)
  File "/Users/bdraco/home-assistant/homeassistant/components/camera/__init__.py", line 630, in handle
    image = await _async_get_image(
  File "/Users/bdraco/home-assistant/homeassistant/components/camera/__init__.py", line 166, in _async_get_image
    image_bytes = await camera.async_camera_image(
  File "/Users/bdraco/home-assistant/config/custom_components/unifiprotect/camera.py", line 287, in async_camera_image
    last_image = await self.upv_object.get_snapshot_image(
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 347, in get_snapshot_image
    return await self.api_request_raw(f"cameras/{camera_id}/snapshot", params=params, raise_exception=False)
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/pyunifiprotect/api.py", line 187, in api_request_raw
    await self.ensure_authenticated()
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/pyunifiprotect/api.py", line 265, in ensure_authenticated
    await self.authenticate()
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/pyunifiprotect/api.py", line 281, in authenticate
    response = await self.request("post", url=url, json=auth)
  File "/Users/bdraco/home-assistant/venv/lib/python3.9/site-packages/pyunifiprotect/api.py", line 161, in request
    raise NvrError(f"Call {url} received 404 Not Found")
pyunifiprotect.exceptions.NvrError: Call https://192.168.210.83/api/auth/login received 404 Not Found
```

**Comment by AngellusMortis** [comment]
I am about to install a bunch of new switches in my house, so I will be offline for a bit. Will install into my HA instnace and debug afterwards.

**Comment by AngellusMortis** [comment]
Looks good now. Definitely had a bit of a typo there.

**Comment by bdraco** [comment]
Retesting now

**Review by bdraco — APPROVED** [review]
TEST PASS!

**Pull request merged**
