### PR TITLE
Refactor to reduce pylint errors

### PR DESCRIPTION
**Pull request by bdraco**
I broke apart the data process into `unifi_data.py` as `pyunifiprotect/unifi_protect_server.py` was starting to get a bit large.

### CODE REVIEW

**Comment by bdraco** [comment]
Still testing.. looking like I introduced a bug
```
020-10-26 16:25:45 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 124, in update
    self._reset_camera_events()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 322, in _reset_camera_events
    self.device_data[camera_id].update(EMPTY_EVENT)
AttributeError: 'str' object has no attribute 'update'

```

**Comment by bdraco** [comment]
I think this is good to go, but I'm going to run the profiler to make sure the code paths look ok 

I tested it my UDMP and the cloudkey2 system

**Comment by bdraco** [comment]
It looks good.

**Comment by bdraco** [comment]
Screen Shot 2020-10-26 at 11 40 14 AM

Looks good on the profile

**Comment by bdraco** [comment]
We could probably reduce the camera endpoint polling as well.

**Comment by briis** [comment]
Damn you are fast. One day I want to be able to code like you :)
Thank you very much for the assistance, this is awesome.

I'll make the pypi build and adjust the manifest. Then final tests at my side.

**Pull request merged**
