### PR TITLE
Update cameras model live from the websocket

### PR DESCRIPTION
**Pull request by bdraco**
Work in progress

First step to support updating the camera data live so we can know when to switch from using events to the camera model when recording is turned off to see motion.

- [x] To test: verify all the switches still work

### CODE REVIEW

**Comment by bdraco** [comment]
Tested and everything is working as expected except for highFps switches.

However it seems to be an existing issue as the the api call to switch it isn't actually working.

**Comment by briis** [comment]
One question first: Whats your first name?  Mine is Bjarne.
The highFps worked a while ago, but they might have changed the API.

Is this ready to merge for me testing it?

**Comment by bdraco** [comment]
> One question first: Whats your first name? Mine is Bjarne.

My first name is actually `John`, but I use my middle name, `Nick` since so many people in my family are named `John` and it gets a bit confusing.  My github shows as `J. Nick Koston`

> The highFps worked a while ago, but they might have changed the API.
> 
> Is this ready to merge for me testing it?

Yes!

**Comment by briis** [comment]
I'll call you Nick then. 👍 

I'll merge and start testing.

**Comment by briis** [comment]
Everything seems to work very well. It is night here, so I will test a bit more in daylight. (All my G4's are outside)
With regards to highFps. I can get it to work partially: I can turn it off from HA but I cannot turn it back on. Switch state is also updated correctly, when I turn it on or off from the Protect App. So it just seems that the ON command is wrong.

**Pull request merged**
