### PR TITLE
Adds has_highfps calculated feature flag

### PR DESCRIPTION
**Pull request by AngellusMortis**
Calculated feature flag to make the switch on the HA easier to do.

### CODE REVIEW

**Review by bdraco — APPROVED** [review]

**Review by bdraco — APPROVED** [review]

**Comment by AngellusMortis** [comment]
Do not merge this one yet. I am going to add a few more calculated ones.

**Comment by AngellusMortis** [comment]
Should be good for now. That will let me get the rest of the switch / number entities.

**Review by bdraco — APPROVED** [review]

**Comment by bdraco** [comment]
Test looks like it needs a fixup
```
  >               assert not camera_obj.is_privacy_on
  E               AssertionError: assert not True
  E                +  where True = Camera(model=<ModelType.CAMERA: 'camera'>, id='0a6ec595956ef5a5c5d646c3', name='Pkc Udi', type='UVC G4 Pro', mac='8D92...s_managed=True, last_ring_event_id=None, last_smart_detect=None, last_smart_detect_event_id=None, talkback_stream=None).is_privacy_on
```

**Comment by AngellusMortis** [comment]
On top of it. My mistake for not running the tests locally first.

**Pull request merged**
