### PR TITLE
Creates release workflow

### PR DESCRIPTION
**Pull request by AngellusMortis**
This workflow needs a PyPi API token secret added to use.

1. Go to https://pypi.org/manage/account/token/
2. Create a token for "Project: pyunifiprotect"
3. Go to https://github.com/briis/pyunifiprotect/settings/secrets/actions
4. Add "New repository secret" named `PYPI_API_TOKEN` with the value from above

### CODE REVIEW

**Comment by briis** [comment]
This is now done. Hope it works.

**Comment by AngellusMortis** [comment]
I copied and pasted it from one that I knew was working. Only difference is `build` instead of `flit` for building the package. Same upload process though. I will merge it and test it out once @bdraco gets a chance to look at https://github.com/briis/pyunifiprotect/pull/124 and merge it.

**Comment by briis** [comment]
If I wanted to use this for some of the other projects I have, would I have to change anything, except for the token reference?

**Comment by AngellusMortis** [comment]
You _might_ need to change steps 3 and 4. Since [PEP 517](https://www.python.org/dev/peps/pep-0517/), there is a standard for making builders. So, you can use whatever builder you want now. Step 3 is "install requirements for builder" (in this case `build`, but I also mentioned I used `flit` on another package of mine). Step 4 is "build the package".

**Comment by AngellusMortis** [comment]
Here is the other project I pulled it from. As you can see, it is identical except for steps 3/4 https://github.com/AngellusMortis/sxm-player/blob/master/.github/workflows/release.yml

Then here is the Github template for uploading a package on release: https://github.com/briis/pyunifiprotect/new/master?filename=.github%2Fworkflows%2Fpython-publish.yml&workflow_template=python-publish

That is what I originally based mine off of.

**Comment by AngellusMortis** [comment]
It worked. https://pypi.org/project/pyunifiprotect/1.2.1/

**Pull request merged**
