### PR TITLE
Add websocket support

### PR DESCRIPTION
**Pull request by bdraco**
Thanks to @hjdhjd for decoding the protocol

Fixes https://github.com/briis/pyunifiprotect/issues/4

here: https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/ProtectAPI.md?rgh-link-date=2020-09-08T14%3A30%3A43Z

### CODE REVIEW

**Comment by briis** [comment]
Perfect. Thanks. I have build and uploaded it pypi.org as 0.21.0

**Comment by briis** [comment]
Hi @bdraco 
I just installed my old CloudKey, to verify that all is running. And everything is except for the Event part. So no Motion Events are fired on the Cameras. To me it seems that the polling does not start for the CloudKey? Can you see if this is true?

**Comment by briis** [comment]
Did more testing. The `async_refresh` function in the *data* module, IS called every 2 seconds when running a CloudKey. But the Binary Sensor does not get updated with Motion status. I keep debugging to see if I can find the reason.

**Comment by briis** [comment]
After a bit more testing - it is the pyunifiprotect module, that does not return any data.

Line 140 in unifi_protect_server.py (`updates = await self._get_events(10)`) is always returning an empty array.

**Comment by bdraco** [comment]
> After a bit more testing - it is the pyunifiprotect module, that does not return any data.
> 
> 
> 
> Line 140 in unifi_protect_server.py (`updates = await self._get_events(10)`) is always returning an empty array.
> 
> 

I got access to my neighbors setup which is using a cloud key.  I'll start testing shortly

**Comment by bdraco** [comment]
I wasn't able to replicate the issue.  Its working as expected for me.

Screen Shot 2020-10-26 at 9 11 12 AM

```
2020-10-26 14:11:38 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping camera update
2020-10-26 14:11:38 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] get_events: https://192.168.213.128:7443/api/events params={'end': '1603721508000', 'start': '1603721488000'}
2020-10-26 14:11:38 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] events = [{'type': 'motion', 'start': 1603721485720, 'end': 1603721493546, 'camera': '5f96d735011aed03e70003eb', 'score': 43, 'id': '5f96d910030c7c03e7000406', 'metadata': {'objectType': None, 'objectCoords': None, 'objectConfidence': None}, 'modelKey': 'event', 'partition': None, 'thumbnail': 'e-5f96d910030c7c03e7000406', 'heatmap': 'e-5f96d910030c7c03e7000406'}]
2020-10-26 14:11:40 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping camera update
2020-10-26 14:11:40 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] get_events: https://192.168.213.128:7443/api/events params={'end': '1603721510000', 'start': '1603721490000'}
2020-10-26 14:11:40 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] events = [{'type': 'motion', 'start': 1603721485720, 'end': 1603721493546, 'camera': '5f96d735011aed03e70003eb', 'score': 43, 'id': '5f96d910030c7c03e7000406', 'metadata': {'objectType': None, 'objectCoords': None, 'objectConfidence': None}, 'modelKey': 'event', 'partition': None, 'thumbnail': 'e-5f96d910030c7c03e7000406', 'heatmap': 'e-5f96d910030c7c03e7000406'}]
2020-10-26 14:11:42 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] Skipping camera update
2020-10-26 14:11:42 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] get_events: https://192.168.213.128:7443/api/events params={'end': '1603721512000', 'start': '1603721492000'}
2020-10-26 14:11:42 DEBUG (MainThread) [pyunifiprotect.unifi_protect_server] events = [{'type': 'motion', 'start': 1603721485720, 'end': 1603721493546, 'camera': '5f96d735011aed03e70003eb', 'score': 43, 'id': '5f96d910030c7c03e7000406', 'metadata': {'objectType': None, 'objectCoords': None, 'objectConfidence': None}, 'modelKey': 'event', 'partition': None, 'thumbnail': 'e-5f96d910030c7c03e7000406', 'heatmap': 'e-5f96d910030c7c03e7000406'}]
```

**Comment by briis** [comment]
I added another Camera to the Cloudkey, so there is now a G3 Flex and a G3 Bullet. Funny thing is that the G3 Bullet is working as expected, but not the G3 Flex. And that worked earlier, as it was attached to my UDMP. I'll try and unmanage and readopt it and see if it works.

**Comment by bdraco** [comment]
> I added another Camera to the Cloudkey, so there is now a G3 Flex and a G3 Bullet. Funny thing is that the G3 Bullet is working as expected, but not the G3 Flex. And that worked earlier, as it was attached to my UDMP. I'll try and unmanage and readopt it and see if it works.

Do you see the events in the protect UI?

**Comment by bdraco** [comment]
I synced to master and still working

**Comment by briis** [comment]
I think this was Error 40 - In Europe this is, the error is sitting 40 cm from the Keyboard - Me.
I tweaked the Motion Sensitivity on the G3 Flex camera, and now it works, and registers motion in HA also.
Sorry for this.

**Comment by bdraco** [comment]
I'll do some more testing on a system that is still using a cloudkey2 that is on HST.  It will be a few more hours before its daylight there and I can ask someone to waive to the camera.

**Comment by briis** [comment]
Very good. I'll also continue the testing here, and I have a little tweak to do based on other requests. So the master will change with the next 30 minutes or so. I'll upload as 0.22.4

**Comment by bdraco** [comment]
I think we need to catch NVRError in the websocket as well.  I'll send something soon.
```
2020-10-26 12:38:34 ERROR (MainThread) [custom_components.unifiprotect.data] Error while updating
Traceback (most recent call last):
  File "/config/custom_components/unifiprotect/data.py", line 48, in async_refresh
    await self._protectserver.update(
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 127, in update
    await self._get_camera_list()
  File "/usr/local/lib/python3.8/site-packages/pyunifiprotect/unifi_protect_server.py", line 408, in _get_camera_list
    raise NvrError(
pyunifiprotect.unifi_protect_server.NvrError: Fetching Camera List failed: 500 - Reason: Internal Server Error
```

**Comment by briis** [comment]
Oh, I did not see this. What did you do to get that error?

**Comment by bdraco** [comment]
> Oh, I did not see this. What did you do to get that error?

Protect just happens to throw it every so often.  I think its a bug

**Comment by briis** [comment]
I have gotten a few Issues on this, but never figured out why it happened. So glad to know that you think this a Protect Bug. Perfect if you can make the program handle the error gracefully.
I did a new update, so please sync the master again.

**Comment by bdraco** [comment]
To close the loop on this, its definitely working on the cloudkey g2 plus system on HST 

Screen Shot 2020-10-26 at 1 17 35 PM

Aloha!

**Comment by briis** [comment]
Yes, I see the same. Both my CloudKey and my UDMP, runs like a well tuned engine, thanks to you.

**Comment by hjdhjd** [comment]
You will need to handle several types of errors from the controller. 500 is only one of several options. You also will need to time-bound it. Some requests can take several seconds to return and will hang. In looking through the code, I think the one area that really needs to be made more robust in connectivity to the controller:

- Incremental backoff / reconnect (I believe someone implemented this).
- Handling errors when requesting snapshots (happens up to 5% of the time in busier controller environments).
- Handling long return times - snapshots should return instantaneously, but in practice can take 5-10 seconds in some instances. This can cause other things to hang if you’re dealing with things synchronously.

Good luck guys!

**Comment by bdraco** [comment]
> 
> * Incremental backoff / reconnect (I believe someone implemented this).
> * Handling errors when requesting snapshots (happens up to 5% of the time in busier controller environments).
> * Handling long return times - snapshots should return instantaneously, but in practice can take 5-10 seconds in some instances. This can cause other things to hang if you’re dealing with things synchronously.
> 
> Good luck guys!

Thanks for the tips!

**Pull request merged**
